### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Roms1383** [Roms1383/test-flutter-rust-bridge#1]
When running:
```sh
RUST_BACKTRACE=full flutter_rust_bridge_codegen --rust-input src/api.rs --dart-output src/bridge_generated.dart
```
It doesn't compile with the error:
```sh
[2022-01-03T15:47:48Z INFO  flutter_rust_bridge_codegen] Picked config: Opts { rust_input_path: "/Users/romain/Development/contributions/test-flutter-rust-bridge/src/api.rs", dart_output_path: "/Users/romain/Development/contributions/test-flutter-rust-bridge/src/bridge_generated.dart", c_output_path: "/var/folders/st/8cddrx857yj1gh8yvj0j499c0000gn/T/.tmp5QyxZN.h", rust_crate_dir: "/Users/romain/Development/contributions/test-flutter-rust-bridge", rust_output_path: "/Users/romain/Development/contributions/test-flutter-rust-bridge/src/bridge_generated.rs", class_name: "TestFlutterRustBridge", dart_format_line_length: 80, skip_add_mod_to_lib: false, llvm_path: "", llvm_compiler_opts: "" }
[2022-01-03T15:47:48Z INFO  flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2022-01-03T15:47:48Z INFO  flutter_rust_bridge_codegen] Phase: Parse AST to IR
[2022-01-03T15:47:48Z INFO  flutter_rust_bridge_codegen] Phase: Transform IR
[2022-01-03T15:47:48Z INFO  flutter_rust_bridge_codegen] Phase: Generate Rust code
[2022-01-03T15:47:48Z INFO  flutter_rust_bridge_codegen] Phase: Generate Dart code
[2022-01-03T15:47:48Z INFO  flutter_rust_bridge_codegen] Phase: Other things
[2022-01-03T15:47:48Z WARN  flutter_rust_bridge_codegen::commands] command="sh" "-c" "dart pub global run ffigen --config /var/folders/st/8cddrx857yj1gh8yvj0j499c0000gn/T/.tmpqz63aa" stdout= stderr=No active package ffigen.
    
thread 'main' panicked at 'command execution failed. command="sh" "-c" "dart pub global run ffigen --config /var/folders/st/8cddrx857yj1gh8yvj0j499c0000gn/T/.tmpqz63aa"', /Users/romain/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.11.0/src/commands.rs:81:9
stack backtrace:
   0:        0x100d5e7c0 - std::backtrace_rs::backtrace::libunwind::trace::h3788418f13e49f6e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x100d5e7c0 - std::backtrace_rs::backtrace::trace_unsynchronized::hf189cd7ee07b4d2b
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100d5e7c0 - std::sys_common::backtrace::_print_fmt::hcd10aea219dfc188
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x100d5e7c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha9fb0042c142196e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x100d7afa8 - core::fmt::write::ha61991bf8ecf136a
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:        0x100d5b2cc - std::io::Write::write_fmt::h46c2e7b09a3411d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:        0x100d600ac - std::sys_common::backtrace::_print::h66fb61bcb7af7f3c
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x100d600ac - std::sys_common::backtrace::print::hd77bcd12ac793f65
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x100d600ac - std::panicking::default_hook::{{closure}}::h2e75467530bdcca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:        0x100d5fc78 - std::panicking::default_hook::habe288fd56f5750a
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:        0x100d60718 - std::panicking::rust_panic_with_hook::h0de8caef2b5cd059
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:628:17
  11:        0x100d60238 - std::panicking::begin_panic_handler::{{closure}}::hacf45a4761576516
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:        0x100d5ec98 - std::sys_common::backtrace::__rust_end_short_backtrace::hc8935facac9e6044
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x100d601a0 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:        0x100d8d47c - std::panicking::begin_panic_fmt::hc3ed556f40157c45
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
  15:        0x100b503d4 - flutter_rust_bridge_codegen::commands::execute_command::h6962582e22902f35
  16:        0x100b4fbd4 - flutter_rust_bridge_codegen::commands::bindgen_rust_to_dart::h18475b41866109e9
  17:        0x100b747d0 - flutter_rust_bridge_codegen::utils::with_changed_file::h12d2ac0bb5aed775
  18:        0x100b7971c - flutter_rust_bridge_codegen::main::h3ace202f4954c722
  19:        0x100b76bec - std::sys_common::backtrace::__rust_begin_short_backtrace::h90ce29f45477b75b
  20:        0x100b44fe4 - std::rt::lang_start::{{closure}}::h84722357b075e7b7
  21:        0x100d60b64 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h51c1d4e6d77bdcbb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  22:        0x100d60b64 - std::panicking::try::do_call::h89fe052533bafbda
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  23:        0x100d60b64 - std::panicking::try::h46d7f0e49ad79887
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  24:        0x100d60b64 - std::panic::catch_unwind::h39132fca9d95ef81
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  25:        0x100d60b64 - std::rt::lang_start_internal::{{closure}}::h6539b3c59dc74c9d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  26:        0x100d60b64 - std::panicking::try::do_call::h5b104bf56577bb16
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  27:        0x100d60b64 - std::panicking::try::h7769cac6f81ef323
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  28:        0x100d60b64 - std::panic::catch_unwind::h3b24c77fb952102f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  29:        0x100d60b64 - std::rt::lang_start_internal::hb4d1fe995f6e94ee
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  30:        0x100b7a454 - _main
```

**Comment by fzyzcjy** [comment]
Maybe raise the issue in flutter_rust_bridge ;)
